version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: entrega_sistemas-db-1
    environment:
      SA_PASSWORD: "TuPasswordSeguro123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d
    
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P TuPasswordSeguro123 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: entrega_sistemas-redis-1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./proyectofinal
    container_name: entrega_sistemas-api-1
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=metodos_db;User Id=sa;Password=TuPasswordSeguro123;TrustServerCertificate=True
      - ConnectionStrings__Redis=redis:6379
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: ./worker
    container_name: entrega_sistemas-worker-1
    stdin_open: true
    tty: true
    environment:
      - DB_SERVER=db
      - DB_NAME=metodos_db
      - DB_USER=sa
      - DB_PASSWORD=TuPasswordSeguro123
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy